@startuml
interface IAttackAble {
    + AttackForCollEnable() : void
    + AttackForCollDisEnable() : void
}
interface ISkillAble {
    + UseSkillFirstTiming(skillIndex:int) : void
    + UseSkillSecondTiming(skillIndex:int) : void
}
@enduml
