@startuml
class PlayerEquipment {
    +  <<event>> onEquipmentChanged : OnEquipmentChanged 
    + Equip(newItem:WeaponItem) : void
    + Unequip() : WeaponItem
}
MonoBehaviour <|-- PlayerEquipment
PlayerEquipment --> "equippedWeapon" WeaponItem
@enduml
