@startuml
class Emote {
    + <<override>> CanStartAction(controller:RPGCharacterController) : bool
    + <<override>> CanEndAction(controller:RPGCharacterController) : bool
    # <<override>> _StartAction(controller:RPGCharacterController, emoteType:EmoteType) : void
    # <<override>> _EndAction(controller:RPGCharacterController) : void
}
class "BaseActionHandler`1"<T> {
}
"BaseActionHandler`1" "<EmoteType>" <|-- Emote
@enduml
