@startuml
class Talk {
    + <<override>> CanStartAction(controller:RPGCharacterController) : bool
    + <<override>> CanEndAction(controller:RPGCharacterController) : bool
    # <<override>> _StartAction(controller:RPGCharacterController, context:int) : void
    # <<override>> _EndAction(controller:RPGCharacterController) : void
}
class "BaseActionHandler`1"<T> {
}
"BaseActionHandler`1" "<int>" <|-- Talk
@enduml
