@startuml
class Move {
    + Move(movement:RPGCharacterMovementController)
    + <<override>> CanStartAction(controller:RPGCharacterController) : bool
    # <<override>> _StartAction(controller:RPGCharacterController, context:EmptyContext) : void
    + <<override>> IsActive() : bool
}
class "MovementActionHandler`1"<T> {
}
"MovementActionHandler`1" "<EmptyContext>" <|-- Move
@enduml
