@startuml
class HandlerTypes {
    + {static} <<readonly>> Aim : string = "Aim"
    + {static} <<readonly>> Attack : string = "Attack"
    + {static} <<readonly>> Block : string = "Block"
    + {static} <<readonly>> Cast : string = "Cast"
    + {static} <<readonly>> AttackCast : string = "AttackCast"
    + {static} <<readonly>> Crouch : string = "Crouch"
    + {static} <<readonly>> Death : string = "Death"
    + {static} <<readonly>> Dodge : string = "Dodge"
    + {static} <<readonly>> Emote : string = "Emote"
    + {static} <<readonly>> EmoteCombat : string = "EmoteCombat"
    + {static} <<readonly>> Face : string = "Face"
    + {static} <<readonly>> HipShoot : string = "HipShoot"
    + {static} <<readonly>> Injure : string = "Injure"
    + {static} <<readonly>> Null : string = "Null"
    + {static} <<readonly>> Reload : string = "Reload"
    + {static} <<readonly>> Shoot : string = "Shoot"
    + {static} <<readonly>> SlowTime : string = "SlowTime"
    + {static} <<readonly>> Sprint : string = "Sprint"
    + {static} <<readonly>> Strafe : string = "Strafe"
    + {static} <<readonly>> Turn : string = "Turn"
    + {static} <<readonly>> ClimbLadder : string = "ClimbLadder"
    + {static} <<readonly>> AcquiringGround : string = "AcquiringGround"
    + {static} <<readonly>> Crawl : string = "Crawl"
    + {static} <<readonly>> Fall : string = "Fall"
    + {static} <<readonly>> Idle : string = "Idle"
    + {static} <<readonly>> Move : string = "Move"
    + {static} <<readonly>> Navigation : string = "Navigation"
    + {static} <<readonly>> Relax : string = "Relax"
    + {static} <<readonly>> Roll : string = "Roll"
    + {static} <<readonly>> Knockback : string = "Knockback"
    + {static} <<readonly>> Knockdown : string = "Knockdown"
    + {static} <<readonly>> Swim : string = "Swim"
    + {static} <<readonly>> MaintainingGround : string = "MaintainingGround"
    + {static} <<readonly>> GetHit : string = "GetHit"
    + {static} <<readonly>> SwitchWeapon : string = "SwitchWeapon"
    + {static} <<readonly>> Switch : string = "Switch"
    + {static} <<readonly>> Charge : string = "Charge"
    + {static} <<readonly>> DiveRoll : string = "DiveRoll"
    + {static} <<readonly>> Jump : string = "Jump"
    + {static} <<readonly>> DoubleJump : string = "DoubleJump"
    + {static} <<readonly>> Talk : string = "Talk"
}
@enduml
