@startuml
class DayDurationController {
    + Duration : float
    - Awake() : void
}
MonoBehaviour <|-- DayDurationController
DayDurationController --> "Sky" GameObject
DayDurationController --> "Glow" GameObject
@enduml
