@startuml
class RootMotionHandler {
    - Awake() : void
    - OnAnimatorMove() : void
}
MonoBehaviour <|-- RootMotionHandler
RootMotionHandler --> "DeltaPos" Vector3
RootMotionHandler --> "DeltaRot" Quaternion
RootMotionHandler --> "_animator" Animator
@enduml
